/*
AUTOR: PATRICK COVRE RODRIGUES
DATA: 22/02/2024
FUNÇÃO: QUANDO O BOTÃO "PARAM_ADIAPRORROG FOR ACIONADO ELE DA UM UPDATE NA TABELA PRORROGFIN COM A NOVA DATA DE PAGAMENTO E QUEM FOI O SOLICITANTE E OS SYSDATE"
 */
CREATE OR REPLACE PROCEDURE ADIA_PRORROG(
	P_CODUSU NUMBER,        -- Código do usuário logado
	P_IDSESSAO VARCHAR2,    -- Identificador da execução. Serve para buscar informações dos parâmetros/campos da execução.
	P_QTDLINHAS NUMBER,     -- Informa a quantidade de registros selecionados no momento da execução.
	P_MENSAGEM OUT VARCHAR2 -- Caso seja passada uma mensagem aqui, ela será exibida como uma informação ao usuário.
) AS
	PARAM_ADIARPRORROG NUMBER;
	FIELD_NUPRO NUMBER;
	P_NOMEUSU VARCHAR(40);
BEGIN

	PARAM_ADIARPRORROG := ACT_INT_PARAM(P_IDSESSAO, 'ADIARPRORROG');

	FOR I IN 1..P_QTDLINHAS
	LOOP
	SELECT NOMEUSU INTO P_NOMEUSU FROM TSIUSU WHERE CODUSU = P_CODUSU;
	
	FIELD_NUPRO := ACT_INT_FIELD(P_IDSESSAO, I, 'NUPRO');
	
	IF PARAM_ADIARPRORROG IS NOT NULL THEN
		UPDATE AD_PRORROGFIN SET DHADIA = NOVADTPAG + PARAM_ADIARPRORROG, OBSPRORROG = 'Foi solicitado pelo código do usuário [' || P_CODUSU || ']. Nome usuário [' || P_NOMEUSU ||'], Data de solicitação [' || SYSDATE || ']'  WHERE NUPRO = FIELD_NUPRO;
		INSERT INTO TSILIB (NUCHAVE,EVENTO,TABELA,CODUSUSOLICIT,DHSOLICIT,CODUSULIB,OBSERVACAO, REPROVADO,VLRLIMITE,VLRATUAL) 
		VALUES (FIELD_NUPRO,1036, 'AD_PRORROG', P_CODUSU, SYSDATE, 349, 'Foi solicitado pelo código do usuário [' || P_CODUSU || ']. Nome usuário [' || P_NOMEUSU ||'], Data de solicitação [' || SYSDATE || ']' , 'N',0,0);
	END IF;

	END LOOP;

	P_MENSAGEM := 'FEITO';

END;